name: stable deploy
on:
  push:
    branches:
      - stable
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install and Build
      run: |
        npm install --legacy-peer-deps
        npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with: 
        ACCESS_TOKEN: ${{ secrets.ACTION_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
